# Functions that are 'exported' by the package (i.e. visible to package users).



#' Remove duplicate columns that are generated by REDCap's data import code
#'
#' REDCap generates R code to import data and label it, which is great. But when it does
#' labels and levels factor columns, it makes a copy of the original column (for example,
#' `original` copied into `original.factor`) that doesn't even have the labels from the
#' original, which is bad.
#'
#' This function:
#'
#' 1. Copies the labels from `original` into `original.factor`,
#' 2. removes `original`,
#' 3. renames `original.factor` to `original`.
#'
#' @param df (Dataframe) A dataframe imported using REDCap's auto-generated R code.
#'
#' @return A dataframe.
#' @export
#'
#' @importFrom magrittr %>%
shrink_redcap_cols <- function(df) {
    # ---- 1. Identify the columns to operate on ----

    # First, identify the columns suffixed with '.factor'.
    suffixed_cols <- stringr::str_subset(colnames(df), "^.*?\\.factor$")

    # Removing the '.factor' suffix *should* give a list of the original columns.
    unsuffixed_cols <- stringr::str_remove_all(suffixed_cols, "\\.factor$")

    # This is the order of columns in the original dataframe, minus the .factor cols.
    # It will be needed for re-ordering the columns at the end.
    col_order <- stringr::str_subset(colnames(df), "^.*?\\.factor$", negate = TRUE)


    # ---- 2. Copy labels from original cols to their copies ----

    # To copy the labels from the original columns into the `.factor` copies, they need to
    # be in separate dataframes and be renamed identically.

    vars_to_keep <-  # Has the .factor cols
        df %>%
        dplyr::select(dplyr::any_of(suffixed_cols)) %>%
        # copy_labels_from() requires the paired columns to have identical names
        dplyr::rename_with(~ stringr::str_remove(., "\\.factor"))

    vars_to_discard <-  # Has the original cols
        df %>%
        # any_of() is always used here for safety, in case some columns don't exist.
        dplyr::select(dplyr::any_of(unsuffixed_cols))

    labelled_suffixed_vars <-  # Has the .factor cols, with labels copied in
        vars_to_keep %>%
        labelled::copy_labels_from(vars_to_discard)

    # ---- 3. Fix and reorder columns ----

    fixed_df <-
        df %>%
        # Delete all of these columns.
        dplyr::select(-dplyr::ends_with(unsuffixed_cols),
                      -dplyr::ends_with(suffixed_cols)) %>%
        # Bind the new labelled and renamed columns back in.
        dplyr::bind_cols(labelled_suffixed_vars) %>%
        # Re-sort the variable names back to their original order.
        dplyr::relocate(dplyr::any_of(col_order), dplyr::everything())


    all_cols_present <- all(unsuffixed_cols %in% colnames(fixed_df))

    if (all_cols_present) {
        return(fixed_df)
    } else {
        stop("The resulting dataframe is missing some of the expected columns.",
             "\n",
             "The missing columns are:",
             "\n",
             desiderata::fold(unsuffixed_cols[!unsuffixed_cols %in% colnames(fixed_df)],
                              n = Inf))
    }
}



#'
#'
#'
#'
#' @export
#'
#' @examples
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'
#'



    }
}
